### ISSUE TITLE
2.3.0 fails to compile with -fno-common

### ISSUE THREAD

**Issue by candrews** [notspiff/audiodecoder.timidity#32]
When compiling with the `-fno-common` CFLAG (which is the default in GCC 10 and later), compilation fails. The first few of those errors are:
```
/usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: lib/timidity/CMakeFiles/timidity_1.dir/timidity/sdl_c.c.o:(.bss+0x10): multiple definition of `global_pink_noise_light'; lib/timidity/CMakeFiles/timidity_1.dir/timidity/buffer_a.c.o:(.bss+0x0): first defined here
/usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: lib/timidity/CMakeFiles/timidity_1.dir/timidity/sdl_c.c.o:(.bss+0x40): multiple definition of `multi_eq_xg'; lib/timidity/CMakeFiles/timidity_1.dir/timidity/buffer_a.c.o:(.bss+0x20): first defined here
/usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: lib/timidity/CMakeFiles/timidity_1.dir/timidity/sdl_c.c.o:(.bss+0x260): multiple definition of `eq_status_gs'; lib/timidity/CMakeFiles/timidity_1.dir/timidity/buffer_a.c.o:(.bss+0x240): first defined here
```
Here's the full build output: https://734934.bugs.gentoo.org/attachment.cgi?id=651842

Here's some background, including how to fix this issue: https://wiki.gentoo.org/wiki/Gcc_10_porting_notes/fno_common

Originally reported downstream at https://bugs.gentoo.org/734934

**Comment by AlwinEsch** [comment]
I'm on a update round by audiodecoders, can look to fix it, thanks for the report.

**Comment by AlwinEsch** [comment]
Have done a heavy update round and seems work with `-no-common` (has also leaved them now in build flags) :grin: 
Related changes are available here https://github.com/xbmc/audiodecoder.timidity/pull/31.

**Comment by AlwinEsch** [comment]
Is now fixed with this release https://github.com/xbmc/audiodecoder.timidity/releases/tag/3.0.0-Matrix
